### ISSUE TITLE
consider using recent ghc's callstack to get call-site information instead of TH

### ISSUE THREAD

**Issue by ibotty** [Soostone/katip#10]

**Comment by MichaelXavier** [comment]
That's an interesting suggestion. Are you referring to `currentCallStack :: IO [String]`? Here are a few concerns I have

1. In order for `currentCallStack` to provide anything useful, the executable must be compiled with profiling enabled. This is not always trivial. I have some projects whose dependencies don't compile under executable profiling. I also have been lead to believe that profiling interacts poorly with some compiler optimizations and may not be a good reasonable default.
2. In order for `currentCallStack` to always provide detailed call stacks, something like `fprof-auto` needs to be used, because it only annotates functions which have been SCC annotated.
3. I'm not 100% clear about the overhead of calling `currentCallStack` on every invocation of a long command.

Please let me know if it was another feature you were referring to that better deals with these concerns.

**Comment by ibotty** [comment]
No I am talking about `getCallStack :: CallStack -> [(String, SrcLoc)]`, i.e. callstacks via implicit parameters. Regarding performance, callstacks pass an implicit parameter around, getCallStack is its accessor, so it's exactly like passing `(String, SrcLoc)]` explicitly. When statically known, I am sure it inlines perfectly (or would with a few `INLINE` pragmas in `base` and `INLINE` on your logging function (to lazy to look up the name right now)).
