### ISSUE TITLE
[katip-elasticsearch] Example with custom IndexSetings does not compile

### ISSUE THREAD

**Issue by vlatkoB** [Soostone/katip#102]
Hi, 
tried uncommenting settings in the example
```defaultEsScribeCfgV5 { essIndexSettings = IndexSettings (ShardCound 1) (ReplicaCount 0)}```
but can't get it to compile, to find the right combination of type annotations.

Could you help? Using 8.4.4, if it's relevant.

**Comment by MichaelXavier** [comment]
Can you show me the error you're getting?

**Comment by MichaelXavier** [comment]
Try this: `defaultEsScribeCfgV5 { essIndexSettings = IndexSettings (ShardCound 1) (ReplicaCount 0)} :: ESScribeCfg ESV5`

I just pushed that to master. I think the issue is that `IndexSettings` is typed as the GADT `IndexSettings v`, and when you do a record update like this, you could change what the type variable `v` refers to. So you have to tell GHC that you still want it to be ESV5.

**Comment by MichaelXavier** [comment]
I'm not opposed to changing approaches. The approach I chose was perhaps short sighted in that i didn't want to maintain two parallel implementations of all the logging machinery when the portion of the API I was using was the same across versions. If that's going to be untenable going forward, it may warrant another work. 

Perhaps there may be a way to write an implementation that is heavily parametric and/or takes something like an explicit dictionary. The machinery of katip-elasticsearch at the shared core could then be a pretty general expression of what has to be done and each version supported could just inject their implementation to make that expression concrete. I'd love if somebody sketched out a proposal here. As for me, I'm moving slow because I'm still basically the last person on earth stuck in ES1.

**Comment by vlatkoB** [comment]
Like DSL with the specific interpreter for each ES version? Very interesting approach.

I did the `Bloodhound V6` which passes all the tests (not yet tested by others), but when I tried to implement it as `ESV6` in `Katip`, 4 tests failed so I switched back to `ES5`.
```
data ESV6 = ESV6

instance ESVersion ESV6 where
  type BHEnv ESV6 = V6.BHEnv
  type IndexSettings ESV6 = V6.IndexSettings
  type UpdatableIndexSetting ESV6 = V6.UpdatableIndexSetting
  defaultIndexSettings _ = V6.defaultIndexSettings
  type IndexName ESV6 = V6.IndexName
  toIndexName _ = V6.IndexName
  fromIndexName _ (V6.IndexName x) = x
  type MappingName ESV6 = ()   -- removed mapping param
  fromMappingName _ _ = ""
  type DocId ESV6 = V6.DocId
  toDocId _ = V6.DocId
  type BH ESV6 = V6.BH
  runBH _ = V6.runBH
  type TemplateName ESV6 = V6.TemplateName
  toTemplateName _ = V6.TemplateName
  type TemplatePattern ESV6 = V6.TemplatePattern
  toTemplatePattern _ = V6.TemplatePattern
  type IndexTemplate ESV6 = V6.IndexTemplate
  toIndexTemplate _ patt sett (mapp:_) = V6.IndexTemplate [patt] sett mapp
  toIndexTemplate _ _ _ _ = error "Only 1 mappings allowed in V6"
  type IndexDocumentSettings ESV6 = V6.IndexDocumentSettings
  toUpdatabaleIndexSettings _ s = (V6.NumberOfReplicas (V6.indexReplicas s)) :| []
  defaultIndexDocumentSettings _ = V6.defaultIndexDocumentSettings
  indexExists _ = V6.indexExists
  indexDocument _ idx _ = V6.indexDocument idx  -- removed mapping param
  createIndex _ = V6.createIndex
  updateIndexSettings _ = V6.updateIndexSettings
  putTemplate _ = V6.putTemplate
  putMapping _ idx _ = V6.putMapping idx   -- removed mapping param
  unanalyzedStringSpec _ = object
    [ "type" .= String "keyword"
    ]
  analyzedStringSpec _ = object
    [ "type" .= String "text"
    ]
```
Could be something in logic, maybe `toIndexTemplate` where mappings are not list any more. Or I messed up something else. I don't have time to dig deeper now.
