### ISSUE TITLE
Question: How to log already created Item?

### ISSUE THREAD

**Issue by vlatkoB** [Soostone/katip#109]
Hi,
I'm testing a central network logging and made a scribe that sends `Item`(s) to the central server for logging in one place, so the server receives an already constructed `Item` with all the log data.
That received `Item` should be logged via any `Scribe` defined on the central server, just as a standard `log*` action would do. So, I'd need a log function with params of `liPush`.

What would be the best way to achieve that?

**Comment by MichaelXavier** [comment]
If I'm understanding correctly, you're trying to forward `Items` from logging agents to a server which will then fan them out to `Scribe`s. If I were to attempt this, I'd probably piggyback on the `Item`'s `ToJSON` and `FromJSON` instances. On the agent side I'd serialize the `Item` and deserialize it on the server side. If the server and client both have access to the payload type `a`, you could decode it directly, otherwise you may need to decode it to something generic like `Item Value`.

The part where this hits a rough edge is that all the log combinators are at too high a level to log an `Item` directly. They generate an `Item` from various components of one. The `LogEnv` has a field `_logEnvScribes :: Map Text ScribeHandle`. A `ScribeHandle` holds a reference to a `Scribe` and a `TBMQueue WorkerMessage`. The [actual code that writes to a scribe](https://github.com/Soostone/katip/blob/master/katip/src/Katip/Core.hs#L957) looks like this:

```haskell
      FT.forM_ (M.elems _logEnvScribes) $ \ ScribeHandle {..} -> do
        whenM (scribePermitItem shScribe item) $
          void $ atomically (tryWriteTBQueue shChan (NewItem item))
```

So in order for you to achieve what you'd want you'd have to reach pretty far into the guts and basically reproduce this logic.

Would you be interested in submitting a PR that extracts an exported and documented function `logFullItem :: (LogItem a, Katip m) => Item a -> m ()` from the code I referenced and rewrites `logItem` in terms of `logFullItem`? It would pull the log env via the `Katip` typeclass then do the same logic as I pasted above. You could even suggest that this is useful for creating centralized logging services.

**Comment by vlatkoB** [comment]
Have I understood correctly that only [this](https://github.com/vlatkoB/katip) is needed?

Maybe a little bikeshedding on the `logFullItem` name?
It is clear from the code that is its intention, but from a user point of view, not very clear in my opinion.
The best would be to rename/repurpose current `logItem`, but that would be a breaking change, so maybe like `logKatipItem`, `logItemObject/record`, `your proposals`. :-)

**Comment by MichaelXavier** [comment]
Exactly what I was looking for. Thank you!

I agree with this probably being better named as `logItem`, but unfortunately that would break API and I'm not sure if that's worth it. I think of the options you present, `logKatipItem` communicates the sort of internal nature of this without actually hiding it away in an internal module. I can't really think of a better name, so let's go with that. Once you make that change, I'll accept the PR and do a release.

**Comment by vlatkoB** [comment]
OK, `logKatipItem` it is. How do you want me to increase the version?

**Comment by MichaelXavier** [comment]
This is additive so I think we'd go `0.8.2.0` -> `0.8.3.0`
