### ISSUE TITLE
Is there a way to avoid nesting with Katip when we are adding context at multiple levels?

### ISSUE THREAD

**Issue by psilospore** [Soostone/katip#137]
If I add logging to the following logic:

```haskell
do
  a <- f "hi"
  b < - g a
  foo a b
```

I might do the following given that f, g, and foo also have logging I want to add context to and I have short-circuiting logic (e.g. Either)

```haskell
do
  a <- f "hi"
  katipAddContext (sl "a" (show a)) $ do
    b <- g a
    katipAddContext (sl "b" (show b)) $ do
      foo a b
```
where f, g, and foo also have logging

**Comment by psilospore** [comment]
In this case I would prefer:

```haskell
do
  a <- f "hi"
  katipAddContext (sl "a" (show a))
  b <- g a
  katipAddContext (sl "b" (show b))
  foo a b
```

**Comment by MichaelXavier** [comment]
The disadvantage to the second approach is that the context is no longer lexically scoped so you can't really tell where the context you've added applies. Katip was really designed to be used like a `Reader`, so that's why we have typeclass functions in `KatipContext` like `localKatipContext :: (LogContexts -> LogContexts) -> m a -> m a`. You could technically make your own `KatipContextT` that wraps a `StateT` instead of a `ReaderT` and then implement `localKatipContext` and the others in terms of `modify'`. Then you could write a `katipAddContext' ctx = katipAddContext ctx (pure ())`. I wouldn't do it personally because I think it could lead to confusing log contexts but that's up to you to decide if it's worth it.
