### ISSUE TITLE
printf-esque format strings, variable arguments

### ISSUE THREAD

**Issue by bitemyapp** [Soostone/katip#24]
This was a long-standing issue I had with fast-logger/monad-logger, but which is slightly exacerbated with needing to `logStr` things.

```haskell
-- Most of my code is going to look like this.
$(logTM) DebugS ("Session was: " ++ logStr (tshow sess))
```

Wondering if perhaps I shouldn't be doing this stuff as a context, with the message just being hand-written? If so, is there a way to do so without a lot of grief? The example from the…example seemed too verbose for context-one-offs in one do block.

```haskell
    addNamespace "confrabulation" $ addContext (ConfrabLogCTX 42) $ do
      $(logTM) DebugS "Confrabulating widgets, with extra namespace and context"
      confrabulateWidgets
    $(logTM) InfoS "Namespace and context are back to normal"
```

How should I go about this?

**Comment by mightybyte** [comment]
Since I'm using katip-elasticsearch, I discovered that things are more easily searchable with kibana after switching from the former to the latter.  Here's what I would have done with your second example:

    addNamespace "confrabulation" $ addContext (sl "sess_ctx" sess) $ do
      $(logTM) DebugS "start_confrabulating"
      confrabulateWidgets
    $(logTM) InfoS "end_confrabulating"

I try to make my msg strings one word and use underscores to make it so kibana doesn't treat them as separate words, which makes individual msg strings more searchable.  YMMV though.

**Comment by bitemyapp** [comment]
Let me be more clear, I'm looking to make the UX less like this:

```haskell
-- Most of my code is going to look like this.
$(logTM) DebugS ("Session was: " ++ logStr (tshow sess))
```

And more like this:

```haskell
$(logTM) DebugS "Session was: %s " sess
```

Or:

```haskell
$(logTM) DebugS [| Session was: ${sess} |]
```

**Comment by MichaelXavier** [comment]
So as for adding contexts, in real applications I'm fairly liberal with adding contexts. I usually end up with 1 or 2 ad-hoc datatypes for holding log context. They're almost never even exported from the module. I think if you conceivably want to search against it, it should go in a context. What would be really cool is if you could truly on-the-fly mash up existing types with LogItem instances into an ad-hoc datatype and provide a default instance that combined instances sensibly. Something like `addContext (userID .: orderID) ...` and the `.:` constructor would take the relevant `LogItem` instances and combine them. As you can tell though, this is less than half baked at the moment. Doug has pointed out the version of this we have today which is actually pretty nice and I wish I didn't keep forgetting about its existence: `addContext (sl "user_id" userID <> sl "order_id" orderID)`.

As for the other issue of overly verbose messages, I get it. I often include info in both context and the message because when I'm reading logs I usually look at messages first and then drill into attributes, so I want those messages to contain useful information for me the human, as well as useful information for the search engine once I'm onto something.

I can golf down your example a bit so that its really not much longer, and indeed this is how my code looks: `$(logTM) DebugS ("Session was: " <> showLS sess)`. 

I'm not opposed to the printf approach bit it presents some issues:
1. We probably don't want to have to maintain 2 parallel APIs (at least not permanently), the old, monoidal style and the printf style. So this would be a significant breaking API change. The only way I could see having our cake and eating it too here is if we did not change the arity of these functions, so if it was something like `$(logTM) DebugS ("Session was: %s " % sess)` where % was some `LogStr` formatting combinator. The nice thing there is any existing code that's doing `"foo " <> ls foo` would simply be parsed as a printf with no interpolation and would require no update. I'm not up to date on the fancy haskell printf solutions out there to know if this would be possible.
2. We should consider if  this would complicate the type signatures too much. I've already seen some complaints that katip is "too complex" and while I generally disagree, I want to make sure I get folks opinions on how complex we're getting.

**Comment by bitemyapp** [comment]
@MichaelXavier I don't think precisely a printf-esque API is needed if I can get contexts to be more lightweight somehow, but the scaffolding to make a datatype is bleh. Ever seen someone abuse generics for shoving a record into an `Object`?

**Comment by mightybyte** [comment]
It seems to me that this kind of formatting really belongs in a standalone library.  You can already do something like this:

    $(logTM) DebugS $ printf "Session was: %s" sess

...modulo the minor potential issue of string conversion and type class instances.  If printf is your target, then it's trivial to create a little helper function that would take care of this.  Perhaps that is a small addition that could be made to katip?  The same idea should work with any other pretty printer that outputs to String or similar.  I don't see any reason for katip to force the choice of pretty printing library on its users.

**Comment by bitemyapp** [comment]
@mightybyte printf is dead, just trying to figure out how to make contexts lighter weight now.

**Comment by MichaelXavier** [comment]
@bitemyapp ok now we're getting somewhere. Do you have a critique of the `sl` approach above? The two downsides I can see are:

1. You write out the keys at the call site so if you have the same context that you want to reconstruct at multiple call sites, it would be better to write a helper function or just write a separate datatype.
2. You give up granular control over which keys different verbosity admits. `sl` assumes `V0` means emit no keys and everything else emits all keys. But again, if you need something more granular than that, I don't see how you'd get away with not writing an instance unless you're going for the `Generics` and unioning different log types together.

**Comment by bitemyapp** [comment]
```
Prelude> from (Id "blah")
M1 {unM1 = M1 {unM1 = M1 {unM1 = K1 {unK1 = "blah"}}}}
```

Sigh, yeah. Best I could do is augment a glorified tuple with the a typerep from Typeable.

I could probably make `sl` work, probably use RWC to remove some noise. I'll call it closed until I've kicked it around. Thank you!
