### ISSUE TITLE
Supporting MonadLogger

### ISSUE THREAD

**Issue by bitemyapp** [Soostone/katip#27]
``` haskell
instance (MonadIO m) => MonadLogger (LoggingT m) where
  monadLoggerLog loc source loglevel msg =
    logFM (levelToSeverity loglevel) (logStr (fromLogStr (toLogStr msg)))
```

I feel like I'm doing it wrong or that it's kind of dirty, but I didn't see any other way to make stuff like [withPostgresqlConn](http://hackage.haskell.org/package/persistent-postgresql-2.2.2/docs/Database-Persist-Postgresql.html#v:withPostgresqlConn) behave.

Not saying this would necessarily make sense _inside_ katip proper, but maybe some boilerplate to mention? I'm not certain it is a good idea to fwomp the bytestring builder into a text builder like that to begin with.

**Comment by MichaelXavier** [comment]
It would probably be pretty easy for me to write a benchmark and see what's the fastest conversion method. I mentioned this in the other ticket, but what do you think about having a package that lives in this repo called `monad-logger-katip-compat` that contains this orphaned instance? Do you think people would use it?

As for perf, I think the idea is that this would be the minimal possible effort to start moving a codebase to Katip and/or a way to get libraries you don't control like persistent onboard, so as long as we're not doing something totally stupid with message conversion, I think we'd be fine.

**Comment by bitemyapp** [comment]
I'd be fine with an official instance, an orphan makes me less than thrilled, but I imagine you want to avoid the dependency yeah?

**Comment by MichaelXavier** [comment]
Exactly. Imagine a world where there's even more than one logging framework in common use in the Haskell ecosystem. Our dependencies could get complicated fast :P

**Comment by MichaelXavier** [comment]
POC is [here](https://github.com/Soostone/katip/compare/27-monadlogger-compat?expand=1). What do you think?

**Comment by MichaelXavier** [comment]
@bitemyapp Just a reminder to you to check this out. I assume you went ahead and already orphaned an instance yourself. Perhaps you could try out this branch and if all looks good, I can release it. Thanks!

**Comment by bitemyapp** [comment]
@MichaelXavier the behavior of the instance looks fine, I think the issue is the potential conflict/overlap. is this something anyone would ever want to override/modify?

**Comment by MichaelXavier** [comment]
@bitemyapp I may misunderstand the issue but the idea is that this would be released as a separate compat package. You would only install it if you were writing an application (not a library), because you'd knowingly be adding an orphaned instance that you intend to use. If you wanted to write your own, you wouldn't depend on this package. I see it as similar to [quickcheck-instances](https://hackage.haskell.org/package/quickcheck-instances).

One issue I can vaguely imagine is if a library defined katip instances (which is fine) in a way such that the end user when using this package would get an undecidable instance? I'm not sure how or if that could happen.

**Comment by bitemyapp** [comment]
@MichaelXavier I think I understand your point. I'd say go ahead and I can try using this myself. Thank you!

**Comment by MichaelXavier** [comment]
I think this is in line with our approach to Katip in general. We had it running for a year before releasing it. Unless there's a pressing need, I always prefer to let enterprising folk (or myself if I need it) put some mileage on it before releasing it.

**Comment by bitemyapp** [comment]
@MichaelXavier certainly a lot easier to do so when Stack makes it simple to pull dependencies from a git repo.

**Comment by NicolasT** [comment]
You may be interested in https://github.com/NicolasT/kontiki/tree/1f40d76e91ab8dd342511fee9b46401a25ed31b6/monad-logger-katip

This package is currently not released on Hackage or anything, it's just something I need for another project.

Rationale: I like to use Katip in an application, but don't want to impose it's usage in libraries, where the `MonadLogger` interface provides enough functionality. Hence the glue.

Goal:
- Not relying on `UndecidableInstances`
- Orphans go in a separate module
- Provide helpers to implement `MonadLogger` for custom `Katip` or `KatipContext` based stacks
- Allow using `MonadLogger` in `Katip` stacks without requiring orphan instances

Content of the package:
- Orphan `MonadLogger` instances for `KatipT` and `KatipContextT` in `Control.Monad.Logger.Katip.Orphans`
- Actual implementation in `Control.Monad.Logger.Katip`. Two parts: some functions one can use to implement `MonadLogger` for any custom `Monad` which implements `Katip` or `KatipContext`, `defaultMonadLoggerLog`, which then takes a 'handler' for which default implementations are provided: `katipLogItem` in case only a `Katip` environment is available, otherwise `katipContextLogItem` for `KatipContext` environments.

Finally, there's a monad transformer, `KatipLoggingT`, which can be used when there's a `Katip` context available in some stack, but no `MonadLogger` instance is provided and one wants to avoid defining an orphan instance. See https://github.com/NicolasT/kontiki/blob/1f40d76e91ab8dd342511fee9b46401a25ed31b6/monad-logger-katip/test/Main.hs#L76 where `MyMonad` has a `Katip` instance but no `MonadLogger` instance.
