### ISSUE TITLE
Hang on use of finalizer. 

### ISSUE THREAD

**Issue by mckeankylej** [Soostone/katip#31]
When running this example: 

    {-# LANGUAGE TemplateHaskell #-}

    import Network.HTTP.Client
    import Katip
    import Katip.Scribes.ElasticSearch
    import Database.Bloodhound

    main :: IO ()
    main = do
      mgr <- newManager defaultManagerSettings
      (es,finalizer) <- mkEsScribe defaultEsScribeCfg (mkBHEnv (Server "http://localhost:9200") mgr)
                                  (IndexName "diamond") (MappingName "diamond") InfoS V3
      le <- registerScribe "elasticSearch" es <$> initLogEnv "main" "development"
      runKatipContextT le () "minimalCase" ($(logTM) InfoS $ "Testing hang")
      finalizer

The code terminates if the finalizer is not run. If you run the finalizer the code hangs indefinitely. 
We are using docker-elk for the server. 
Nothing ever gets written to elasticsearch.

**Comment by MichaelXavier** [comment]
@mckeankylej So I ran this code and indeed I saw the issue but here's what it was for me: the ElasticSearch handler for Katip inherits `defaultIndexSettings` from bloodhound, which sets a shard count of 3 and replica count of 2. If you're running this on a single node, ES does the arguably reasonable thing of trying to write replicas but cannot meet write consistency. It tries for 60 seconds and katip has a retry policy of exponential backoff with 5 retries, so *eventually* the write will give up and the program will terminate. If you try running the write in your HTTP client of choice you may see something like this:

```
{
  "status": 503,
  "error": "UnavailableShardsException[[diamond-2016-6-6][2] Not enough active copies to meet write consistency of [QUORUM] (have 1, needed 2). Timeout: [1m], request: index {[diamond-2016-6-6][diamond][3ad68310-1d64-48f5-80c4-22a2ab49eab3], source[{\"foo\": \"bar\"}]}]"
}
// PUT http://localhost:9200/diamond-2016-6-6/diamond/3ad68310-1d64-48f5-80c4-22a2ab49eab3
// HTTP/1.1 503 Service Unavailable
// Content-Type: application/json; charset=UTF-8
// Content-Length: 283
// Request duration: 60.005949s
```

So the solution would be to:
1. Set a lower write quorum.
2. Configure your index settings to be appropriate to your cluster. Here's an example:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}
import Network.HTTP.Client
import Katip
import Katip.Scribes.ElasticSearch
import Database.Bloodhound

main :: IO ()
main = do
  let esCfg = defaultEsScribeCfg { essIndexSettings = defaultIndexSettings { indexReplicas = ReplicaCount 0} }
  mgr <- newManager defaultManagerSettings
  (es,finalizer) <- mkEsScribe esCfg (mkBHEnv (Server "http://localhost:9200") mgr)
                              (IndexName "diamond") (MappingName "diamond") InfoS V3
  le <- registerScribe "elasticSearch" es <$> initLogEnv "main" "development"
  runKatipContextT le () "minimalCase" ($(logTM) InfoS $ "Testing hang")
  putStrLn "running finalizer"
  finalizer
```

Now, considering I walked right into this without suspecting it was the issue, I think at least there should be a section in the documentation on this. I hesitate to change the default index settings because they are sensible defaults for a production environment. I was thinking of just adding a section on configuring your index in the haddocks. Please try the above code out, let me know if it solves your issue and if my solution sounds reasonable. Thanks!

**Comment by mckeankylej** [comment]
This solves my issue! I think you should lower to default because it might turn off beginners using the libarary if the defaults dont work for a simple example. Regardless thanks.
