### ISSUE TITLE
Support for working with index templates

### ISSUE THREAD

**Issue by mightybyte** [Soostone/katip#32]
I'm trying to set up an index template to make sure that some of my fields have the correct type, but I'm running into the problem described here.

http://stackoverflow.com/questions/36225751/elasticsearch-template-not-creating-new-index-in-elasticsearch-1-7

Is it possible to have katip-elasticsearch specify the mappping when adding documents so index templates can be used to control data types?

**Comment by MichaelXavier** [comment]
I may misunderstand the problem but if you set up date-based (or custom) sharding for the scribe, rather than create a mapping just for the given index name, it will create a template, so if your index name is `production-logs` it will create a template matching `production-logs-*`. See relevant code [here](https://github.com/Soostone/katip/blob/master/katip-elasticsearch/src/Katip/Scribes/ElasticSearch.hs#L276)

You'll find that it sets up just a base-level mapping of just the static fields that katip will produce. It can't possibly know all of the fields your application logs will produce, so it leaves those to be inferred. If you did however know all of the fields or perhaps just a subset that you wanted to control because inference would do the wrong thing (such as analyze a string that you intend to search by exact match), you could update the mapping it creates, either by pulling down the mapping and extending it or by me exposing `baseMapping` from `katip-elasticsearch`. Or I could go with something less kludgy if you have any ideas.

**Comment by mightybyte** [comment]
Oh, you can completely disregard this.  The index template that was being created was wrong, so I assumed it was something that elasticsearch created by default.  Turns out some of my data was getting converted to string before it got to the logs, so it is behaving correctly.  Sorry for the noise.
