### ISSUE TITLE
example of how to remove items from the context

### ISSUE THREAD

**Issue by ababkin** [Soostone/katip#44]
first of all - great logging framework, I was able to follow the example and docs and set up a basic logger.
I'd like to remove some of the fields from the context though: like the `host`, `thread` and the `process id`
I was not able to figure out how to do this in 30min or so

Is there an example anywhere on how to easily add/remove fields from the context? This would be very helpful

Thanks

**Comment by MichaelXavier** [comment]
I assume you're using the elasticsearch scribe? The fixed fields of an `Item` like the ones you mentioned are automatically captured by the library and I don't think there's a neat seam in the scribe layer that would let you censor those out, as the type is `newtype Scribe = Scribe (forall a. LogItem a => Item a -> IO ())`. 

So right now the only way I could see this working is to write your own scribe. Obviously this is almost certainly overkill because things like the ElasticSearch scribe are nontrivial. A solution that would require a change in the library would be to add a field to `EsScribeConfig` that would configure it, maybe something like `omitFields :: [Text]`. It just feels kind of hacky. Maybe there's another way? Also note that this would turn it into something solved on a per-scribe basis.

**Comment by ababkin** [comment]
thanks @MichaelXavier 

I'm using it to write to a local log file currently
I'll play around with `katip` some more to figure this out and will report back if i succeed
