### ISSUE TITLE
Re-implementing monad-logger's filterLogger

### ISSUE THREAD

**Issue by bitemyapp** [Soostone/katip#57]
Sorry to bother you! Here's some context:

https://github.com/kazu-yamamoto/logger/blob/3d47a7b4d0b21ddb2821a3892779636f9e3b1e1c/monad-logger/Control/Monad/Logger.hs#L726-L731

(inlining)

```haskell
newtype LoggingT m a =
  LoggingT { runLoggingT :: (Loc -> LogSource -> LogLevel -> LogStr -> IO ()) -> m a }

filterLogger :: (LogSource -> LogLevel -> Bool)
             -> LoggingT m a
             -> LoggingT m a
filterLogger p (LoggingT f) = LoggingT $ \logger ->
    f $ \loc src level msg ->
        when (p src level) $ logger loc src level msg
```

Whereas in my neck of the woods:

```haskell
data LogState = LogState {
    _lsNamespace   :: Namespace
  , _lsLogContexts :: LogContexts
  , _lsLogEnv      :: LogEnv
  }

newtype LoggingT m a = LoggingT {
      unLoggingT :: ReaderT LogState m a
    } deriving (MonadReader LogState,
                Functor, Applicative, Monad,
                MonadIO, MonadMask,
                MonadTrans, MonadThrow, MonadCatch)
```

Which is more or less in accordance with the examples in the library I think. Here's my problem:

1. I can't patch over the behavior of the logger action(s) as functions

2. I'd like to be able to filter log messages out of the logs by textual or structural content (Persistent in this case)

I see a couple ways to address this, but wanted to know if this was a use-case the library was meant to explicitly accommodate like `monad-logger`'s `filterLogger` or if there's a method you'd recommend.

**Comment by MichaelXavier** [comment]
I may need a rephrasing on problem number 1, I don't think I quite understand. As for filtering out logs, here's what we've got today:

Katip has the notion of Severity and Verbosity. By convention, scribes take a severity level and verbosity level. Severity is used (via the `permitItem` function) to determine *whether* an item will be logged, i.e. if you configure a scribe for Info logging, it should discard Debug messages. I'm not super happy about the fact that this is only a convention, but there hasn't really been a huge proliferation of alternative scribes  so that issue hasn't been forced.

Verbosity determines which keys from a payload object should actually be recorded. The idea is you could create a custom payload object with a *lot* of info, but if you usually keep your verbosity under V3, you're not paying the disk space cost for all the extraneous keys.

So, circling back to your question, it does not sound like verbosity is of interest because you want to omit entire messages. Severity may also be too imprecise because if you've wired persistent into Katip and its doing info logging, you may actually disagree with the messages they choose to be info level and will want to censor those out yourself. I guess I'd need to know more about the criteria for your filtering, but note that a scribe is a newtype over `forall a. LogItem a => Item a -> IO ()` so without any modification you would be able to wrap a function over that that tossed out forbidden log messages I'd think.

**Comment by bitemyapp** [comment]
>I may need a rephrasing on problem number 1, I don't think I quite understand. As for filtering out logs, here's what we've got today:

Given what you said about the `Scribe`, I think it's wrong anyway. Seems like what I want is to make a modified scribe.

>you may actually disagree with the messages they choose to be info level and will want to censor those out yourself

Basically yes, the old code that was wrapped around `monad-logger` was a bit dirty, but it was checking for the `SQL` sub-string in the text message passed to the logger and filtering it out on `True`.

>Seems like what I want is to make a modified scribe.

This seems to be the answer, as long as I can get the information I need from `Item (LogItem a => a)`. Thank you! I'll report back when I've had a chance to take a crack at it.

**Comment by MichaelXavier** [comment]
@bitemyapp how'd that go?

**Comment by bitemyapp** [comment]
@MichaelXavier Not gotten to it, but I'll tee it up for my next sprint!

**Comment by MichaelXavier** [comment]
Please reopen if something needs to be done on katip's end.
