### ISSUE TITLE
Question: logging "non-contextual" payload

### ISSUE THREAD

**Issue by BartAdv** [Soostone/katip#62]
Suppose I've got a `saveFoo` function, at beginning of which I'm adding context to track the user and the id of the foo that is gonna be saved:

```haskell
saveFoo :: Maybe ID -> AuthUser AdminRole -> FooEdit -> AppHandler Int64
saveFoo fooId authUser fooEdit = K.katipAddContext (FooCTX user cid) authUser fooId $ do
  ...
``` 

Now, somewhere inside that function, I'm saving some related object, and I want to log that fact, with possibly largest amount of detail. Is adding another context the right thing to do:

```haskell
      K.katipAddContext (K.sl "bar" bar) $
        logFM InfoS "Updating existing bar"
```
?

I'm asking cause I initially had an impression that context are for some, well, contextual data that can possibly be reused among couple of log entries, whereas a single log entry could contain relevant details (aparat from the message itself). But I've noticed that various `logXX` variants want the payload to be the part of the context, and the message is just `LogStr`. Is this the intended usage? Or am I missing something?

**Comment by MichaelXavier** [comment]
Excuse me if I didn't parse this ticket correctly, I've got a cold and its eating my brain. In the example you provided, when you log `Updating exiting bar`, it will take the context object you provided with `FooCTX` and it will add an additional field to it `bar` with the value of `bar`. `katipAddContext` adds contexts by simply merging the context objects underneath the monad you provide it so that if you nest multiple `katipAddContext` within eachother these contexts will be combined.

Katip started out with the idea that you'd want to frequently provide some contextual data alongside the log messages and you can still do that with combinators like `logItem`. However, in practice it became clear that you often obtain context independently of logging messages. So the pattern I usually follow is as soon as some contextual data becomes available that I want to tag into logs, I use `katipAddContext` and then any logging I do within that will automatically carry that context.

Let me know if that didn't answer the question.

**Comment by BartAdv** [comment]
Sorry if I wasn't clear (it's probably my explanation, and not a cold), and thanks for such a prompt answer!

What you've written describes Katip design pretty well, and I understand it. However, I fail to see how I could have more details in my actual messages.

> So the pattern I usually follow is as soon as some contextual data becomes available that I want to tag into logs, I use katipAddContext and then any logging I do within that will automatically carry that context

Yes, and that's pretty great, however, what content do you put in the actual log messages? Just the text strings with explanation of what happened? Or do you also want to put some data there? (like, not only "Updated journal", but suppose "Updated journal, details: ....") Is it possible, or would I have to just convert it to string?

**Comment by MichaelXavier** [comment]
So if you have relevant, structured, contextual information in your context, then what you put in the message is really up to you and how you want to interact with your logs. If you're just using the handle backend and using grep and other tools to process the logs, then the context will always show up to the left of the message so you may want to leave out those redundant details in the message.

However, if you use the elasticsearch backend (and I have more experience with this) and you plan on using Kibana to browse your logs, I'd approach it this way: attach any useful contextual data to the context and then in the message put in only the information that will help you win scanning through the logs. The context is already attached out-of-band to the message so no real need to redundantly `show` it in the message or anything. When I use kibana, I usually start by filtering by severity, namespace, or other attributes. I then read through the messages, find a log that piques my interest and expand it. From there you can actually look at the whole object associated with that log message and add pieces of it to your search criteria. So tl;dr for ES/Kibana: put information in the message string that will catch your eye, don't redundantly show the whole context.

**Comment by BartAdv** [comment]
Thanks for sharing the insights!

I guess part of my problems were due to the fact I somehow missed the `showLS` and I've been wondering why is it so hard to log showable things. This in turn made me think I might be approaching it from wrong angle.
