### ISSUE TITLE
Usage pattern questions

### ISSUE THREAD

**Issue by MichaelXavier** [Soostone/katip#65]
Taking this discussion from email to issues. Tagging in @abailly and @ababkin.

Temporary example is https://github.com/symbiont-io/sym-logging
Test failure illustrated https://github.com/symbiont-io/sym-logging/blob/master/tests/Symbiont/Logging/Test.hs#L203

**Comment by MichaelXavier** [comment]
Ok guys, I thought this would be a more complicated matter so I cloned the repo and ran the tests but I actually think its quite simple. Yes, you need to close your logenv rather than just continually reallocating them. After all, it is a resource like any other. 

For me the tests failed by expecting logs to be there but not seeing them. This make sense because as of katip 0.5, logging went from a not necessarily synchronous operation depending on the scribe (i.e. Handle was synchronous, elasticsearch was not) to an always asynchronous operation because all it has to do is push your message into a queue for each scribe that's active at the time.

Closing scribes gives the author of the scribe a chance to free any resources they allocated at scribe setup. In the handle scribe its important to note that the handle is not closed because the scribe did not allocate it. It would be trivial to add a fully-managed scribe that took a filename instead of a handle and would thus open and close it by itself. However and most importantly: closing scribes first cuts off any new log messages from going to the queues, then works to drain the queues and flush the final output source *synchronously* so that no message are in flight. It is deliberately synchronous so that you can wait for it to finish before sequencing in other cleanup like closing the handle.

Let me know if this clarifies the issue and if you think there's anything to be done documentation wise or otherwise to help make this clearer in katip itself.

**Comment by abailly** [comment]
Thanks a lot for the explanation @MichaelXavier. I definitely think it is a good idea to write asynchronously and this is something I have done in the past for logging and was planning to do in our `Scribe`. You saved me some efforts by providing it in Katip 0.5.0 ! And I understand the rationale for `register/close` symmetry.

What I don't understand clearly is what causes our tests to fail. Even though we don't close the previous scribes, we allocate a fresh new environment and scribe on each test so I would expect some resource leak but not the absence of logging. Peeking at source code, here is what I understand of the sequence of actions:

1. we allocate new env/new scribe and log to it
2. we close the handle without closing scribe which leaves the `ScribeHandle`'s thread running, waiting for more messages that will never come
3. we allocate a new env and scribe with another handle to run in next test which should spawn a new thread reading from a new queue

Given this logical sequence I don't understand why tests after the first one are failing because whatever remains of the previous env should be irrelevant because env is new, internal map of `ScribeHandle`s is also new and the `Handle` we write to is pointing at temp file... 

I am puzzled

**Comment by MichaelXavier** [comment]
@abailly From what I can follow in your code, you're getting your actual log lines for assertion by closing the handle and reading the file, right? Not only does not closing the scribe read the thread running, its queue open, etc, but it also does not cause the logger to flush output that's buffered. I believe the sequence is:

1. Open the log env and set up the handle scribe
2. Send a log message.
3. Message goes into the queue for the worker thread asynchronously.
4. Your main thread closes the handle, does not flush the scribe, reads the entire file which will never include the buffered logs. The scribe may be internally freaking out at this point by trying to write to a closing handle.

I expect if you instead put a delay between when you log and when you close the handle, you'd see your log messages. However, this would only make sense to maybe prove a point about how it works or check understanding. The actual solution is that closing your scribes is the correct thing to do and it will make sure that after `closeScribes` finishes, any log messages in flight will be written.

**Comment by abailly** [comment]
Thanks, I can confirm that adding a delay (instead of closing env) makes the test pass. Of course, the right solution is to call `closeScribes` and that's what we now do, just wanted to be sure I understand the problem clearly.

**Comment by MichaelXavier** [comment]
Cool. Glad we got it figured out!
